
 /******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic.h
 *
 * Description: header file for the Ultrasonic  Sensor driver
 *
 * Author: Abdelrahman Shabrawy
 *
 *******************************************************************************/

#ifndef HAL_ULTRASONIC_ULTRASONIC_H_
#define HAL_ULTRASONIC_ULTRASONIC_H_
/* INCLUDE MICROCONTROLLER ABSTRCTION LAYERS WHICH are ICU and GPIO */
#include "../../MCAL/ICU/icu.h"
#include "../../MCAL/GPIO/gpio.h"
#include "../../LIBRARIES/std_types.h"


/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define ECHOSENSOR_PORT_ID		  PORTD_ID
#define ECHOSENSOR_CHANNEL_ID         6
#define TRIGGERSENSOR_PORT_ID		  PORTB_ID
#define TRIGGERSENSOR_CHANNEL_ID      5
#define SENSOR_MAX_DISTANCE    		500

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * • Description
 *	➢ Initialize the ICU driver as required.
 *	➢ Setup the ICU call back function.
 *	➢ Setup the direction for the trigger pin as output pin through the GPIO driver.
*/

void Ultrasonic_init(void);
/*
 * • Description
 *	➢ Send the Trigger pulse to the ultrasonic.
*/

void Ultrasonic_Trigger(void);

/*
 * •Description
 * 	➢ Send the trigger pulse by using Ultrasonic_Trigger function.
 *	➢ Start the measurements by the ICU from this moment.
*/

uint16 Ultrasonic_readDistance(void);
/*
 *	• Description
 *	 ➢ This is the call back function called by the ICU driver.
 * 	 ➢ This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
*/

void Ultrasonic_edgeProcessing(void);



#endif /* HAL_ULTRASONIC_ULTRASONIC_H_ */
